USE [master]
GO

/****** Object:  Database [Public]    Script Date: 21/12/2024 11:06:05 م ******/
DROP DATABASE [Public]
GO

/****** Object:  Database [Public]    Script Date: 21/12/2024 11:06:05 م ******/
CREATE DATABASE [Public]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Public', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Public.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Public_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Public_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Public].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Public] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Public] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Public] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Public] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Public] SET ARITHABORT OFF 
GO

ALTER DATABASE [Public] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Public] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Public] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Public] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Public] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Public] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Public] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Public] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Public] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Public] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Public] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Public] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Public] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Public] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Public] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Public] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Public] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Public] SET RECOVERY FULL 
GO

ALTER DATABASE [Public] SET  MULTI_USER 
GO

ALTER DATABASE [Public] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Public] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Public] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Public] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Public] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Public] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Public] SET QUERY_STORE = ON
GO

ALTER DATABASE [Public] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Public] SET  READ_WRITE 
GO

